# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: cloud-provider-openstack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"


secret:
  create: true
#  name:

# use keys from here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager
cloudConfig:
  global:
    auth-url:
    username:
    password:
    tenant-id:
    domain-name:
    region:
  networking:
    ipv6-support-disabled: true
    public-network-name:
  loadBalancer:
    internal-lb: false
    floating-network-id:
    create-monitor: true
    # network-id:
    # subnet-id:
  # blockStorage:
  # metadata:


# Check here for config information
# https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

openstack-cinder-csi:
  nameOverride: ""
  fullnameOverride: ""
  timeout: 3m

  csi:
    snapshotController:
      enabled: true
    attacher:
      image:
        repository: k8s.gcr.io/sig-storage/csi-attacher
        tag: v3.3.0
    provisioner:
      image:
        repository: k8s.gcr.io/sig-storage/csi-provisioner
        tag: v3.0.0
    snapshotter:
      image:
        repository: k8s.gcr.io/sig-storage/csi-snapshotter
        tag: v4.2.1
    resizer:
      image:
        repository: k8s.gcr.io/sig-storage/csi-resizer
        tag: v1.3.0
    livenessprobe:
      image:
        repository: k8s.gcr.io/sig-storage/livenessprobe
        tag: v2.5.0
    nodeDriverRegistrar:
      image:
        repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
        tag: v2.4.0
    plugin:
      image:
        repository: docker.io/k8scloudprovider/cinder-csi-plugin
        pullPolicy: IfNotPresent
        tag:  # defaults to .Chart.AppVersion
      volumes:
        - name: cacert
          hostPath:
            path: /etc/cacert
      volumeMounts:
        - name: cacert
          mountPath: /etc/cacert
          readOnly: true
        - name: cloud-config
          mountPath: /etc/kubernetes/
          readOnly: true

  secret:
    enabled: true
    create: false
    name: cloud-config
  storageClass:
    enabled: true
    delete:
      isDefault: true
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true


openstack-cloud-controller-manager:
  image:
    repository: docker.io/k8scloudprovider/openstack-cloud-controller-manager
    tag: "v1.23.0"


  # Any extra arguments for openstack-cloud-controller-manager
  controllerExtraArgs: {}
  # controllerExtraArgs: |-
  #   - --cluster-name=my-cluster

  # Create a service monitor for Prometheus Operator
  serviceMonitor: {}
  # serviceMonitor:
  #   enabled: true

  # Create a secret resource cloud-config (or other name) to store credentials and settings from cloudConfig
  secret:
    create: false
  #  name:
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/controlplane
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    value: "true"
    effect: NoExecute
