# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: cloud-provider-openstack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

storageClass:
  enabled: true
  delete:
    isDefault: true
    allowVolumeExpansion: true
  retain:
    isDefault: false
    allowVolumeExpansion: true

secret:
  create: true
#  name:

# use keys from here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager
cloudConfig:
  global:
    auth-url:
    username:
    password:
    tenant-id:
    domain-name:
    region:
  networking:
    ipv6-support-disabled: true
    public-network-name:
  loadBalancer:
    internal-lb: false
    floating-network-id:
    create-monitor: true
    # network-id:
    # subnet-id:
  # blockStorage:
  # metadata:


# Check here for config information
# https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

openstack-cinder-csi:
  nameOverride: ""
  fullnameOverride: ""
  timeout: 3m


  secret:
    enabled: true
    create: false
    name: cloud-config
  storageClass:
    enabled: false


openstack-cloud-controller-manager:

  # Any extra arguments for openstack-cloud-controller-manager
  controllerExtraArgs: {}
  # controllerExtraArgs: |-
  #   - --cluster-name=my-cluster

  # Create a service monitor for Prometheus Operator
  serviceMonitor: {}
  # serviceMonitor:
  #   enabled: true

  # Create a secret resource cloud-config (or other name) to store credentials and settings from cloudConfig
  secret:
    create: false
  #  name:
  tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/controlplane
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    value: "true"
    effect: NoExecute
