# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: cloud-provider-openstack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"


secret:
  create: true
#  name:

# use keys from here: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#config-openstack-cloud-controller-manager
cloudConfig:
  global:
  networking:
  loadBalancer:
  blockStorage:
  metadata:



# Check here for config information 
# https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

cinder-csi-templates:
    nameOverride: ""
    fullnameOverride: ""
    timeout: 3m

    csi:
      attacher:
        image:
          repository: k8s.gcr.io/sig-storage/csi-attacher
          tag: v2.2.1
      provisioner:
        image:
          repository: k8s.gcr.io/sig-storage/csi-provisioner
          tag: v1.6.1
      snapshotter:
        image:
          repository: k8s.gcr.io/sig-storage/csi-snapshotter
          tag: v2.1.3
      resizer:
        image:
          repository: k8s.gcr.io/sig-storage/csi-resizer
          tag: v0.5.1
      livenessprobe:
        image:
          repository: k8s.gcr.io/sig-storage/livenessprobe
          tag: v2.1.0
      nodeDriverRegistrar:
        image:
          repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
          tag: v1.3.0
      plugin:
        image:
          repository: docker.io/k8scloudprovider/cinder-csi-plugin
          tag:  # defaults to .Chart.AppVersion

    secret:
      enabled: true
      create: false

    storageClass:
      enabled: true
      delete:
        isDefault: false
        allowVolumeExpansion: true
      retain:
        isDefault: true
        allowVolumeExpansion: true




openstack-cloud-controller-manager:
  image:
    repository: docker.io/k8scloudprovider/openstack-cloud-controller-manager
    tag: ""


  # Any extra arguments for openstack-cloud-controller-manager
  controllerExtraArgs: {}
  # controllerExtraArgs: |-
  #   - --cluster-name=my-cluster

  # Create a service monitor for Prometheus Operator
  serviceMonitor: {}
  # serviceMonitor:
  #   enabled: true

  # Create a secret resource cloud-config (or other name) to store credentials and settings from cloudConfig
  secret:
    create: false
  #  name:
